header-library
JacekPasierb/filmonetka pull request #12
Opened 2023-04-17 20:30 UTC by MartaSch

2023-04-18 18:15 UTC, mkubera requested changes

2023-04-18 18:15 UTC, mkubera commented on src/index.js
> +import './js/header_library';
-> `./js/view/header_library`

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +const body = document.querySelector("body");
-> `qs`

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +spanElement.textContent="Filmoteka";
brak frmatowania

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +linkElement.classList.add("header-library__image-link");
(i wiecej linijek)
do przemyslenia: czy nie latwiej byloby uzywac template strings? `<p class="" href="" cokolwiek="innego"> ...`

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +navigations.forEach(function (navigation) {
oodziel enterem

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +const navigations = ["my library", "home"]
to prawdodpodbnie powinny byc stale typu `HOME` i `MY_LIBRARY`.

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +const navigations = ["my library", "home"]
ALBO `PAGE1` I `PAGE2`

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +navigations.forEach(function (navigation) {
-> arr fn

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +   liButtons.prepend(buttonsElement);
-> `<li class="buttons-list"><button class="button" type="button">button</button></li>`

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +   liButtons.prepend(buttonsElement);
czy tekst w buttonie pto powinien byc "button"? o_O

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +element.style.backgroundColor = "var(--button_active)",
klasa raczej niz var

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +element.style.backgroundColor = "var(--button_active)",
brak formatowania (!)

2023-04-18 18:15 UTC, mkubera commented on src/js/header_library.js
> +
martwy kod

2023-04-18 18:15 UTC, mkubera commented on src/sass/partials/_header.scss
> +}
formatowanie (!!!)

2023-04-19 14:54 UTC, JacekPasierb commented on src/js/header_library.js
> +linkElement.classList.add("header-library__image-link");
Faktycznie użyjmy tutaj template strings ;)

2023-04-19 14:55 UTC, JacekPasierb commented on src/js/header_library.js
> +const navigations = ["my library", "home"]
// zmienmy nazwy stałych

2023-04-19 14:59 UTC, JacekPasierb requested changes
Poprawmy może najpierw kod w którym tworzymy wszystko przez DOM, zróbmy przy użyciu template string, Pamiętajmy o funkcjach strzałkowych i formatowaniu. Aha no i te dwie zmienne mogą byc HOME i MY_LIBRARY

2023-04-20 10:22 UTC, JacekPasierb approved these changes

2023-04-20 10:27 UTC, merged