JacekMielanczuk/funkcjonalność do wrzucania do/z local storage
JacekPasierb/filmonetka pull request #14
Opened 2023-04-18 17:26 UTC by JacekMielanczuk

- dodałem funkcje do dodawania do/pobierania z local storage
- trzeba to wpiąć w odpowiednie miejsce i zerknąć czy działa

2023-04-19 14:37 UTC, JacekPasierb commented on src/js/local-storage.js
> +
// Zróbmy arrow funkcje niejawne wszystkie
const getWatchedLocalStorage = () => JSON.parse(localStorage.getItem(KEY_WATCHED));

2023-04-19 14:44 UTC, JacekPasierb commented on src/js/local-storage.js
> +}
// Trzymajmy się stylu importów proponowanych z zajęć, są czytelniejsze

// na dole dodajmy kod coś takiego: 
const local-storage = { watched, queue, getWatchedLocalStorage, getQueueLocalStorage, setWatchedLocalStorage, setQueueLocalStorage, onAddToWatched, onAddToQueue };

export default local-storage;

// troche zabawy ale będzie czytelniej, łatwiej i bardziej zrozumiale.

2023-04-19 14:45 UTC, JacekPasierb requested changes
Zmieńmy funkcje na funkcje strzałkowe wedlug pierwszego schematu co podałem i trrymajmy sie   tego sposobu exportu z komentarz w linijce.

2023-04-19 16:03 UTC, JacekMielanczuk reviewed
Hej, 
Poprawiłem wg Twoich wskazówek

2023-04-21 11:44 UTC, JacekPasierb commented on src/js/local-storage.js
> +export default localStorage;
// eksportujemy tylko localStorage ?? a funkcji nie trzeba ?
moze dodac :

const LS = { getWatchedLocalStorage, getQueueLocalStorage, setWatchedLocalStorage, setQueueLocalStorage, onAddToWatched, onAddToQueue ,localStorage };
export default LS;

2023-04-21 11:45 UTC, JacekPasierb approved these changes
// Zerknij jeszcze w te komentarze

2023-04-21 11:45 UTC, merged